### Text Vectorization

##### Text Vectorization is the process of converting text into numerical representation. Converting Unstructured data to structured data(human readable language)

### Methods to accomplish text vectorization

 - ##### Brinary Term Frequency
  - ##### Bag of Words
  - ##### L1(Normalized Term Frequency)
  - ##### L2(TFIDF)
  - ##### Word2Vec

In [6]:
#loading the dataset  - training data
from sklearn.datasets import fetch_20newsgroups
twenty_train=fetch_20newsgroups(subset="train", shuffle=True)

In [7]:
type(fetch_20newsgroups)

function

In [8]:
twenty_train.data[0]

"From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n"

In [9]:
twenty_train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [10]:
twenty_train.target

array([7, 4, 4, ..., 3, 1, 8])

In [11]:
len(twenty_train.target) # number of target var (y)

11314

In [12]:
set(twenty_train.target)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}

In [13]:
len(twenty_train.data) #number of input records/

11314

In [4]:
#working with text documents: preprocessing and vectorizing :different types

In [ ]:
#types of data: 1.Structured: in numeric form.. csv file which has only numbers
#Unstructured: not in numeric form.. ex: images, text data.

#### Count Vectorizer

##### Count Vectorizer: Provides a simple way to both tokenize a collection of text documents and build a vocabulary of known words

##### Tockenization: basically refers to splitting up a larger body of text into smaller lines, words or even creating words for a non-English Language

In [65]:
text=["The quick brown fox jumped over the lazy dog"]

In [66]:
text

['The quick brown fox jumped over the lazy dog']

In [67]:
from sklearn.feature_extraction.text import CountVectorizer
#list of text documents
#create the transform
vectorizer=CountVectorizer()
#tokenize and build vocab
vector=vectorizer.fit_transform(text)
#summarize

In [68]:
print(vector.shape)
print(vector.toarray())

(1, 8)
[[1 1 1 1 1 1 1 2]]


In [69]:
vectorizer.vocabulary_

{'the': 7,
 'quick': 6,
 'brown': 0,
 'fox': 2,
 'jumped': 3,
 'over': 5,
 'lazy': 4,
 'dog': 1}

In [73]:
#encode another document
text2=["the brown puppy"]
vector=vectorizer.transform(text2)
print(vector.toarray())

[[1 0 0 0 0 0 0 1]]


#### Bag of Words

##### Bag of Words: A bag-of-word model, or BOW for short, is a way of extracting features from text for use in modelling, such as with machine learning algorithms

#### Word Frequencies with TFIDIF

In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer
#list of text documents
text=twenty_train.data
#create the transform
vectorizer=TfidfVectorizer()
#tokenize and build vocab
vectorizer.fit_transform(text)
#summarize

<11314x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [85]:
vector=vectorizer.fit_transform(text)

In [86]:
X=vector.toarray()

In [87]:
X.shape

(11314, 130107)

In [88]:
text[0]

"From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n"

In [89]:
X[0]

array([0., 0., 0., ..., 0., 0., 0.])