### Tensor Flow

- . An open source library developed by google
- . Developed originally to run large numerical computations
- . Accepts data in the form of multidimensional arrays of higher dimensioons called TENSORS
- . Works on the basis of data flow graphs that have nodes and edges

- . Tensor is a generalization of vectors and matrices of potantially higher dimension
- . Tensors are arrays of data with different dimensions and ranks that are fed as input to the neural network.
- . Each computation in Tensor flow is represented as a Data flow graph.

### Program Elements in Tensor Flow
##### Constants-
##### Variable-allows us to add new trainable parameters to graph
##### Placeholders-allows us to feed data to a tensorflow model from outside a model
##### Session-A session is run to evaluate the nodes also known as TensorFlow runtime

#### Demo to Explain Variables, constants and Placeholders

In [94]:
import warnings
warnings.filterwarnings("ignore")

In [95]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [96]:
# this is a variable
zero=tf.Variable(0)

In [97]:
# this is a constant
one=tf.constant(1)

In [98]:
new_value=tf.add(zero, one)

In [99]:
# variable value can be changed 
update=tf.assign(zero, new_value)

In [100]:
# uncomment using demo
# update_constant= tf.assign(zero, new_value)

In [101]:
# init_op=tf.initialize_all_variables()
init_op=tf.global_variables_initializer()

In [102]:
sess=tf.Session()

In [103]:
#initialize the variables
sess.run(init_op)

In [104]:
print(sess.run(zero))
#print(sess.run(one))

0


In [105]:
for _ in range(5):
    sess.run(update)
    print(sess.run(zero))

1
2
3
4
5


In [106]:
# string operations

In [107]:
hello=tf.constant("Hello")

In [108]:
world=tf.constant("world")

In [109]:
helloworld=tf.add(hello,world)

In [110]:
print(sess.run(helloworld))

b'Helloworld'


In [111]:
#placeholder
a=tf.placeholder(tf.float32)

In [112]:
b=a*2

In [113]:
#feeding a placeholder with scalar
result=sess.run(b,feed_dict={a:3})
#result=sess.run(b,{a:3})
print(result)

6.0


In [114]:
#feeding a placeholder with vector of rank 1
results=sess.run(b,feed_dict={a:[3,4,5]})

print(results)

[ 6.  8. 10.]


In [115]:
#feeding a placeholder with multidimmensional vector
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

result=sess.run(b,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [116]:
sess.close()

In [120]:
#common syntax for creating session
#with tf.Session as sess:
#result=sess.run(hello+world)
#print(result)
    #many more lines
    #all lines will be executed within this session
    #no need of explicitly closing the session

In [ ]:
#sess.run(a)

### Demo to explain the TensorFlow Programming Structure

In [121]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [122]:
graph=tf.get_default_graph()

In [123]:
graph.get_operations()

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'init_1' type=NoOp>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_2' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <

In [124]:
a=tf.constant(10,name="a")

In [125]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'init_1' type=NoOp>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_2' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <

In [126]:
#operations[0].node_def

In [127]:
b=tf.constant(20,name= "b")

In [128]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'init_1' type=NoOp>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_2' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <

In [129]:
#c=a+b(=30)
c=tf.add(a,b,name="c")

In [130]:
c

<tf.Tensor 'c_1:0' shape=() dtype=int32>

In [131]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'init_1' type=NoOp>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_2' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <

In [132]:
#d = a*b=200
d=tf.multiply(a,b,name="d")

In [133]:
d

<tf.Tensor 'd_1:0' shape=() dtype=int32>

In [134]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'init_1' type=NoOp>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_2' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <

In [135]:
#e=c*d = 30*200=6000
e=tf.multiply(c,d,name="e")

In [136]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'init_1' type=NoOp>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_2' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <

In [137]:
sess=tf.Session()

In [138]:
print(sess.run(e))

6000


In [139]:
for op in graph.get_operations():print(op.name)

Variable/initial_value
Variable
Variable/Assign
Variable/read
Const
Add
Assign
init
Variable_1/initial_value
Variable_1
Variable_1/Assign
Variable_1/read
Const_1
Add_1
Assign_1
init_1
Const_2
Const_3
Add_2
Placeholder
mul/y
mul
a
b
c
d
e
Variable_2/initial_value
Variable_2
Variable_2/Assign
Variable_2/read
Const_4
Add_3
Assign_2
init_2
Const_5
Const_6
Add_4
Placeholder_1
mul_1/y
mul_1
add_5
a_1
b_1
c_1
d_1
e_1


In [140]:
sess.close()

### Read in the census_data.csv data with pandas

In [141]:
import pandas as pd

In [142]:
census = pd.read_csv("//Users//motolanikay-salami//Downloads//census_data.csv")

In [143]:
census.head()

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   
2   38            Private     HS-grad              9             Divorced   
3   53            Private        11th              7   Married-civ-spouse   
4   28            Private   Bachelors             13   Married-civ-spouse   

           occupation    relationship    race   gender  capital_gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   capital_loss  hours_per_week  native_country income_bracket  
0             0              40   United-States          <=50K  
1             0              13   United-States          <=50K  
2             0              40   United-States          <=50K  
3             0              40   United-States          <=50K  
4             0              40            Cuba          <=50K

##### Tensor flow cannot understand strings as labels,you need to use pandas.apply() method to apply a custom function that converts them to 0s and 1s. 


In [144]:
census['income_bracket'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [145]:
def label_fix(label):
    if label==' <=50k':
        return 0
    else:
        return 1

In [146]:
census['income_bracket'] = census['income_bracket'].apply(label_fix)

##### Perform Train Test Split on census data

In [147]:
from sklearn.model_selection import train_test_split

In [148]:
x_data = census.drop('income_bracket',axis=1)
y_labels = census['income_bracket']
X_train, X_test, y_train, y_test = train_test_split(x_data,y_labels,test_size=0.3,random_state=101)

##### Tensorflow offers an API called estimator

##### model=tf.estimator.LinearClassifier(feature_columns=feat_cols)

##### model.train(input_fn=input_func,steps=5000)

##### prepare feature columns and inputfunction

In [149]:
census.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

In [150]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [151]:
#creating the tf.feature_columns for the categorical values by using vocabulary lists or just using hash buckets

gender = tf.feature_column.categorical_columns_with_vocabulary_list("gender", ["Female", "Male"])
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", hash_bucket_size=1000)
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital status", hash_bucket_size=1000)
relationship =  tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)
education =  tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)
native_country =  tf.feature_column.categorical_column_with_hash_bucket("native_country", hash_bucket_size=1000)

AttributeError: module 'tensorflow_core.compat.v1.feature_column' has no attribute 'categorical_columns_with_vocabulary_list'

In [84]:
#creating the continuous feature_columns for the continuous values using numeric_column

age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")

In [85]:
# put all these variables into a single list with the variable name feat_cols
feat_cols = [gender,occupation,marital_status,relationship,education,workclass,native_country,
             age,education_num,capital_gain,capital_loss,hours_per_week]

NameError: name 'gender' is not defined

In [86]:
#create the input function
#batch size is up to you
input_func=tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=100,num_epochs=None,shuffle=True)

TypeError: pandas_input_fn should not be called without pandas installed

In [87]:
#create your model with tf.estimator
#create a linear classifier
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

NameError: name 'feat_cols' is not defined

In [88]:
#train your model on the data, for at least 5000 steps
model.train(input_fn=input_func,steps=5000)

NameError: name 'model' is not defined

In [89]:
#create a prediction input function 
pred_fn = tf.estimator.inputs.pandas_input_fn(x=X_test,batch_size=len(X_test),shuffle=False) 

TypeError: pandas_input_fn should not be called without pandas installed

In [90]:
# use model.preict()and pass in your input function.
predictions = list(model.predict(input_fn=pred_fn))

NameError: name 'model' is not defined

In [152]:
predictions[0]

NameError: name 'predictions' is not defined

In [153]:
final_preds = []
for pred in predictions:
    final_preds.append(pred['class_ids'][0])

NameError: name 'predictions' is not defined

In [154]:
final_preds[:10]

[]

In [155]:
from sklearn.metrics import classification_report

In [156]:
print(classification_report(y_test,final_preds))

ValueError: Found input variables with inconsistent numbers of samples: [9769, 0]