## Numpy

##### Numpy is the fundamental package for numeric computing with python. it provides powerful ways to create, store and/or manipulate data,which makes it able to seamlessly and speedily integrate with a wide variety of databases

In [5]:
import numpy as np

#### The basics

In [6]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get Dimension
a.ndim

1

In [12]:
b.ndim

2

In [13]:
# Get shape
b.shape

(2, 3)

In [14]:
a.shape

(3,)

In [15]:
# Get type
a.dtype

dtype('int32')

In [16]:
# Get size
a.itemsize

4

In [20]:
# Get total size
a.nbytes

12

### Accesing/Changing specific elements, rows, columns, etc

In [22]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [r,c]
a[1,5]

13

In [24]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# specific column
a[: ,2]

array([ 3, 10])

In [26]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [30]:
a[1,5]=20
print(a)

a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### Initializing Different types of arrays

In [32]:
# ALL 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# ALL 1s matrix
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [35]:
# Any other number
np.full((2,2),99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [36]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal numbers 
np.random.rand(4,2)

array([[0.15894711, 0.0180609 ],
       [0.11674299, 0.85640432],
       [0.69669648, 0.81179051],
       [0.11661594, 0.03960119]])

In [39]:
# Random integer values
np.random.randint(4,8,size=(3,3))

array([[6, 6, 4],
       [4, 4, 5],
       [6, 6, 7]])

In [40]:
# The identity matrix
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# Repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Mathematics

In [47]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a+2

array([3, 4, 5, 6])

In [49]:
a-2

array([-1,  0,  1,  2])

In [50]:
a*2

array([2, 4, 6, 8])

In [51]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [52]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [53]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [54]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear algebra

In [57]:
a=np.ones((2,3))
print (a)


b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [60]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.min(stats)


1

In [62]:
np.max(stats)

6

In [63]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing arrays 

In [64]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [66]:
# vertically stacking vectors 
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])